/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.kavatkedi.kadriye

import kotlinx.cli.*
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.ProgramResult
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.multiple
import com.github.ajalt.clikt.parameters.options.flag
//import dev.kavatkedi.kadriye.dslengine.KadriyeTaskEngine
import dev.kavatkedi.kadriye.dslengine.Kadriye

/*class Kadriye {
	fun run_task(task: String) {
		println("Running $task")
	}
}*/
class KadriyeParseArgs : CliktCommand(help="The build system with less boilerplate. Run the given TASK", name="kadriye"){
	val task by argument()
	val args: List<String> by argument().multiple()
	override fun run() {
		Kadriye.task("hello") { _ -> 
			println("Hello world!")
			0
		}
		Kadriye.task("args") { iargs ->
			if(iargs == null) {
				31
			}
			else {
				for(arg in iargs!!.iterator())
					echo("$arg")

				0
			}
		}
		throw ProgramResult(Kadriye.run(task, args) ?: 31)
	}
}

fun main(args: Array<String>) = KadriyeParseArgs().main(args)
