/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.kavatkedi.kadriye

import kotlinx.cli.*
import dev.kavatkedi.kadriye.dslengine.KadriyeEngine

class Kadriye {
	fun run_task(task: String) {
		println("Running $task")
	}
}

fun main(args: Array<String>) {
	val parser = ArgParser("kadriye")
	val task by parser.argument(ArgType.String, "Task to run")
	val engine = KadriyeEngine()
	parser.parse(args)
	engine.task("hello") {
		_ ->
		println("Hello, world!")
		0
	}
	engine.run(task, args)
	
}
